services:
    db:
        image: mysql:8
        container_name: mysql-container
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
          - mysql:/var/lib/mysql
        networks:
            - api-net
    api:
        build: ./api
        depends_on:
            - db
        container_name: api
        ports:
            - "3030:3030"
        env_file:
            - ./api/.env
        restart: always
        networks:
            - api-net
volumes:
  mysql:
networks:
  api-net: